# directories
app_root: /opt/media
media_files_root: "{{ app_root }}/library"
media_download_root: "{{ app_root }}/download"

# all media libraries and downloads should be accessible by this host group
media_group: media
