# directories
app_root: /opt/media
media_files_root: "{{ app_root }}/library"
media_download_root: "{{ app_root }}/download"
docker_root: "{{ app_root }}/docker"
docker_app_root: "{{ app_root }}/volumes"
docker_log_root: "{{ app_root }}/logs"

# externally visible URL for the media server
media_server_href: http://localhost

# all media libraries and downloads should be accessible by this host group
media_group: media

docker_user: lab-admin
docker_group: docker
docker_subnet: 10.0.0.0/24
docker_timezone: "{{ timezone }}"

docker_services:
  # core services
  socket_proxy:
    addr: 10.0.0.254
    # socket-proxy does not support setting a different container port, so use the default here
    port: 2375
  gluetun:
  homepage:
    port: 3000
  portainer:
    port: 3001
  dozzle:
    port: 3002
  nginx:
    port_http: 3080
    port_https: 3443
    
  # downloaders
  sabnzbd:
    port: 4000
  qbittorrent:
    port: 4001
    
  # feeders
  radarr:
    port: 5000
  prowlarr:
    port: 5001
    
  # media apps
  jellyfin:
    port: 6000
