- hosts: localhost
  become: true
  pre_tasks:
    # XXX skip updating repos while testing
    # - name: update repositories
    #   apt: update_cache=yes
    #   changed_when: False

  tasks:
    - include: tasks/apt_repos.yml
    - include: tasks/packages.yml
