- hosts: localhost
  become: true
  tasks:
    - import_tasks: tasks/apt.yml
      tags: packages
    - import_tasks: tasks/packages.yml
      tags: packages
    - import_tasks: tasks/git.yml
      become_user: "{{ user }}"
      tags: github
    - import_tasks: tasks/dotfiles.yml
      become_user: "{{ user }}"
      tags: dotfiles
    - import_tasks: tasks/emacs.yml
      become_user: "{{ user }}"
      tags: emacs
    - import_tasks: tasks/fonts.yml
      become_user: "{{ user }}"
      tags: fonts

  handlers:
    - import_tasks: handlers/handlers.yml
