- name: Deploy media servers
  hosts: media_servers
  become: true
  pre_tasks:
    - include_vars: secrets/media_servers.yml
      tags: media-server
  roles:
    - role: media-server
      tags: media-server
