- name: Deploy SSL controllers
  hosts: ssl_controllers
  become: true
  pre_tasks:
    - include_vars: secrets/ssl.yml
      tags: ssl-controller
    - include_vars: secrets/dns.yml
      tags: ssl-controller
  roles:
    - role: ssl-controller
      tags: ssl-controller
