- import_playbook: playbook_deploy-lab-hosts.yml
- import_playbook: playbook_deploy-docker-hosts.yml
- import_playbook: playbook_deploy-dns-hosts.yml
- import_playbook: playbook_deploy-ssl-controllers.yml
- import_playbook: playbook_deploy-media-servers.yml
- import_playbook: playbook_deploy-auth-services.yml
- import_playbook: playbook_deploy-docker-core-services.yml
- import_playbook: playbook_deploy-reverse-proxy.yml
