- hosts: lab_hosts
  become: true
  roles:
    - role: lab-host
      tags: lab-host

- hosts: docker_hosts
  become: true
  roles:
    - role: docker-host
      tags: docker-host

- hosts: media_servers
  become: true
  roles:
    - role: media-server
      tags: media-server
