docker_site: auth-services

authentik:
  # NOTE: must match the name of the authentik worker instance defined in service_catalog
  blueprint_root: "{{ docker_volumes_root }}/{{ docker_site }}/authentik-worker/blueprints"
  
  sources:
    - Google
    
  groups:
    - Media Users
    - Docker Admins
    - Test Group

  default_app_groups:
    - Docker Admins

docker_services:
  - postgres
  - redis
  - authentik-server
  - authentik-worker

# docker_services:
#   postgres:
#     port: 5432
#   redis:
#     port: 6380
#   authentik-server:
#     port: 9080
#     port.http: 9080
#     port.https: 9443
#     proxy:
#       base:
#         https://auth.{{ site_name }}
#       require_auth: false
#   authentik-worker:
#     socket_proxy_env:
#       - POST=1
#       - IMAGES=1
#       - CONTAINERS=1
#       - SYSTEM=1

# authentik:
#   # NOTE: must match the name of the authentik worker instance defined in docker_services
#   blueprint_root: "{{ docker_volumes_root }}/{{ docker_site }}/authentik-worker/blueprints"

#   groups:
#     - Media Users
#     - Docker Admins
#     - Test Group
    
#   auth_sources:
#     - Google

#   applications:
#     - name: Hello World 0
#       slug: hello0
#       path: https://hello0.lab0.ianclark.dev
#       # provider_type: proxy
#       groups: [Test Group, Media Users]
#       # auth_sources: [Google]
      
#     - name: Hello World 1
#       slug: hello1
#       path: https://hello1.lab0.ianclark.dev
#       # provider_type: proxy
#       groups: [Test Group]
#       # auth_sources: [Google]

#     - name: Homepage
#       slug: homepage
#       path: https://homepage.lab0.ianclark.dev
#       groups: [Docker Admins]
