docker_site: auth-services

authentik:
  # NOTE: must match the name of the authentik worker instance defined in service_catalog
  blueprint_root: "{{ docker_volumes_root }}/{{ docker_site }}/authentik-worker/blueprints"
  
  sources:
    - Google
    
  groups:
    - Media Users
    - Media Admins
    - Docker Admins
    - Test Group

  default_app_groups:
    - Docker Admins

docker_services:
  - postgres
  - redis
  - authentik-server
  - authentik-worker
