- name: update apt cache
  apt: update_cache=yes
  changed_when: False

- name: install aptitude
  apt:
    name: aptitude
    force_apt_get: yes

- name: perform apt dist-upgrade
  apt:
    upgrade: full

- name: perform apt update
  apt:
    name: "*"
    state: latest
