- name: install emacs dependencies
  apt: name={{item}}
  with_items:
    - gcc
    - automake
    - autotools-dev
    - libmagick++-dev
    - libgtk2.0-dev
    - libxft-dev
    - libgnutls28-dev
    - libdbus-1-dev
    - libgif-dev
    - texinfo
    - libxmp4
    - libxpm-dev


- name: checkout emacs repo
  git:
    repo: git://git.savannah.gnu.org/emacs.git
    dest: ~/apps/src/emacs
    depth: 1
    version: emacs-26.3


- name: build emacs - autogen.sh
  command: >-
    sh autogen.sh
    chdir=~/apps/src/emacs
    creates=~/apps/src/emacs/configure

- name: build emacs - configure
  command: >-
    ./configure --prefix=$HOME/apps --with-x-toolkit=yes
    chdir=~/apps/src/emacs
    creates=~/apps/src/emacs/Makefile

- name: build emacs - make
  command: >-
    make
    chdir=~/apps/src/emacs
    creates=~/apps/src/emacs/src/emacs

- name: build emacs - make install
  command: >-
    make install
    chdir=~/apps/src/emacs
    creates=~/apps/bin/emacs


- name: checkout spacemacs repo
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
