- name: checkout emacs repo
  git:
    repo: git://git.savannah.gnu.org/emacs.git
    dest: "{{ emacs_build_dir }}"
    depth: 1
    version: emacs-{{ emacs_version }}


- name: build emacs - autogen.sh
  command: sh autogen.sh
  args:
    chdir: "{{ emacs_build_dir }}"
    creates: "{{ emacs_build_dir }}/configure"

- name: build emacs - configure
  command: ./configure --prefix={{ app_root | expanduser }} {{ emacs_build_args }}
  args:
    chdir: "{{ emacs_build_dir }}"
    creates: "{{ emacs_build_dir }}/Makefile"

- name: build emacs - make
  command: make
  args:
    chdir: "{{ emacs_build_dir }}"
    creates: "{{ emacs_build_dir }}/src/emacs"

- name: build emacs - make install
  command: make install
  args:
    chdir: "{{ emacs_build_dir }}"
    creates: "{{ app_root }}/bin/emacs"


- name: checkout spacemacs repo
  git:
    repo: https://github.com/syl20bnr/spacemacs
    depth: 1
    dest: ~/.emacs.d


- name: update emacs packages
  command: "{{ app_root }}/bin/emacs --batch -l ~/.emacs.d/init.el --eval='(progn (configuration-layer/update-packages t) (server-force-delete))'"
