- name: checkout all-the-icons repo
  git:
    repo: https://github.com/domtronn/all-the-icons.el.git
    depth: 1
    dest: "{{ app_root }}/src/all-the-icons"

- name: copy all-the-icons fonts
  copy:
    remote_src: yes
    src: "{{ app_root }}/src/all-the-icons/fonts/"
    dest: ~/.fonts/
  notify: reload fc-cache
