- name: install system packages
  apt: name={{item}}
  with_items:
    - linux-headers-amd64
    - gcc
    - perl

- name: install utility packages
  apt: name={{item}}
  with_items:
    - curl
    - screen

- name: install xmonad packages
  apt: name={{item}}
  with_items:
    - libx11-dev
    - libxrandr2
    - libxrandr-dev
    - ghc
    - xmonad
    - cabal-install
    - dmenu
    - dzen2
    - xclip

- name: install python packages
  apt: name={{item}}
  with_items:
    - python-pip
