- name: install system packages
  apt:
    name:
      - linux-headers-amd64
      - gcc
      - perl

- name: install utility packages
  apt:
    name:
      - curl
      - screen
      - tree

- name: install xmonad packages
  apt:
    name:
      - libx11-dev
      - libxrandr2
      - libxrandr-dev
      - libxss-dev
      - libgmp-dev
      - libghc-xmonad-dev
      - libghc-xmonad-contrib-dev
      - dmenu
      - dzen2
      - xclip

- name: install python packages
  apt: name=python-pip

- name: install emacs packages
  apt:
    name:
      - gcc
      - automake
      - autotools-dev
      - libmagick++-dev
      - libgtk2.0-dev
      - libxft-dev
      - libgnutls28-dev
      - libdbus-1-dev
      - libgif-dev
      - texinfo
      - libxmp4
      - libxpm-dev

- name: install font packages
  apt:
    name:
      - fonts-adf-gillius       # Gillius ADF
      - texlive-fonts-extra     # Latin Modern Mono
