- name: install packages
  apt: name={{item}}
  with_items:
    # system
    - linux-headers-amd64
    - gcc
    - perl

    # utilities
    - curl
    - screen

    # xmonad
    - libx11-dev
    - libxrandr2
    - libxrandr-dev
    - ghc
    - xmonad
    - cabal-install
    - dmenu
    - dzen2
    - xclip

    # google chrome
    # - libgif-dev
    # - libgnutls28-dev
    # - google-chrome-stable

    # python
    - python-pip
