- name: install aptitude
  apt:
    name: aptitude
    force_apt_get: yes

- name: install system packages
  apt:
    name:
      - linux-headers-amd64
      - gcc
      - perl

- name: install utility packages
  apt:
    name:
      - curl
      - screen
      - tree

- name: install xmonad packages
  apt:
    name:
      - libx11-dev
      - libxrandr2
      - libxrandr-dev
      - ghc
      - xmonad
      - cabal-install
      - dmenu
      - dzen2
      - xclip

- name: install google chrome packages
  apt: name=google-chrome-stable

- name: install python packages
  apt: name=python-pip
