version: 1
metadata:
  name: Applications - Site Applications
  context: {}
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Applications - Site Providers
    required: true

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Applications ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
{% for name, app in service_catalog.items() if (app | auth_enabled) %}
{% set provider_type = app.auth.type | default("proxy") %}
- model: authentik_core.application
  identifiers:
    slug: {{ name }}
  attrs:
    name: {{ name }}
    meta_launch_url: {{ app.path }}
    policy_engine_mode: any
{% if provider_type == "oauth2" %}
    provider: !Find [authentik_providers_oauth2.oauth2provider, [name, 'Provider for {{ name }}']]
{% elif provider_type == "proxy" %}
    provider: !Find [authentik_providers_proxy.proxyprovider, [name, 'Provider for {{ name }}']]
{% else %}
    provider: "ERROR: unknown auth provider type found in service_catalog.{{ name }}.auth.type: {{ provider_type }}"
{% endif %}
{% endfor %}
