- name: CF-DNS - Create temp file
  local_action:
    module: ansible.builtin.tempfile
  register: tmp
  changed_when: false
  
- name: CF-DNS - Copy script to temp file
  local_action:
    module: ansible.builtin.copy
    src: ../../../submodules/cloudflare-ddns-updater/cloudflare-template.sh
    dest: "{{ tmp.path }}"
    mode: "0644"
  changed_when: false
  
- name: CF-DNS - Update script with custom settings
  local_action:
    module: ansible.builtin.blockinfile
    path: "{{ tmp.path }}"
    insertafter: "^discorduri=\"\""
    block: |
      auth_email="{{ dns.auth_email }}"
      auth_method="{{ dns.auth_method }}"
      auth_key="{{ dns.auth_key }}"
      zone_identifier="{{ dns.zone_id }}"
      record_name="{{ dns.record_name }}"
      ttl="{{ dns.ttl }}"
      proxy="{{ dns.proxy }}"
      sitename="{{ dns.sitename }}"
      slackchannel="{{ dns.slackchannel }}"
      slackuri="{{ dns.slackuri }}"
      discorduri="{{ dns.discorduri }}"
    prepend_newline: true
  changed_when: false
  
- name: CF-DNS - Copy customized script to host
  become: false
  ansible.builtin.copy:
    src: "{{ tmp.path }}"
    dest: "{{ scripts_root }}/update_cf_dns.sh"
    mode: "0750"
    
- name: CF-DNS - Delete temp file
  local_action:
    module: ansible.builtin.file
    path: "{{ tmp.path }}"
    state: absent
  changed_when: false

- name: CF-DNS - Update cron
  become: false
  ansible.builtin.cron:
    name: "CF DNS Update"
    job: "{{ scripts_root }}/update_cf_dns.sh"
    minute: "{{ dns.cron.minute }}"
    hour: "{{ dns.cron.hour }}"
    day: "{{ dns.cron.day }}"
    month: "{{ dns.cron.month }}"
    weekday: "{{ dns.cron.weekday }}"
