- name: Install basic packages
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - ca-certificates
      - curl
      - net-tools

- name: Create root scripts directory
  become: false
  ansible.builtin.file:
    dest: "{{ scripts_root }}"
    state: directory

# TODO setup sshd

- name: Update Cloudflare DNS records
  include_tasks: cf-dns-update.yml
  when: "update_cf_dns"
