- name: Install basic packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - net-tools

- name: Create root scripts directory
  become: false
  ansible.builtin.file:
    dest: "{{ scripts_root }}"
    state: directory

# TODO setup sshd
