- name: Install docker dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download docker repo key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Add docker apt repo
  ansible.builtin.lineinfile:
    line: "deb [arc={{ ansible_facts.architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release | lower }} stable"
    path: /etc/apt/sources.list.d/docker.list
    create: true
    mode: 0644

- name: Install docker packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
