- import_tasks: docker_install_apt.yml
  when: ansible_facts["pkg_mgr"] == "apt"

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ docker_group }}"
    append: true
