- include_vars: secrets/auth_users.yml

- name: Create Authentik blueprints directory
  ansible.builtin.file:
    dest: "{{ authentik.blueprint_root }}"
    state: directory

- name: Copy blueprint template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ authentik.blueprint_root }}/{{ item.path | regex_replace('/', '__') }}"
    owner: root
    group: root
    mode: "0644"
  with_community.general.filetree: ../blueprints
  when: item.state == "file"
  loop_control:
    label: "{{ item.path }}"
