server:
  address: readarr
  port: 8787
config:
  host:
    analyticsEnabled: false
  ui:
    firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
    timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
    uiLanguage: 2 # 1 = English, 2 = French, 3 = Spanish...
rootfolder:
  - name: Books
    path: /data/books
    defaultTags: []
    defaultQualityProfileId: 1
    defaultMetadataProfileId: 1
downloadclient:
  - name: Transmission
    enable: true
    protocol: torrent
    fields:
      - name: host
        value: transmission
      - name: port
        value: 9091
    implementation: Transmission
    configContract: TransmissionSettings
