version: 1
metadata:
  name: Custom User/Group Setup - {{ site_name }}
entries:

  ####################################################
  ### Groups
  ####################################################
    
{% for group in authentik.groups %}
  - id: group-{{ group | lower | replace(' ', '-') }}
    identifiers:
      attributes:
        blueprint-id: group-{{ group | lower | replace(' ', '-') }}
    model: authentik_core.group
    attrs:
      name: {{ group }}
      attributes: {}
    conditions: []
    permissions: []
    state: present
{% endfor %}


  ####################################################
  ### Users
  ####################################################

{% for user in secret_authentik_users %}
  - id: user-{{ user.username | lower | replace('@', '-') | replace('.', '-') }}
    identifiers:
      attributes:
        blueprint-id: user-{{ user.username | lower | replace('@', '-') | replace('.', '-') }}
    model: authentik_core.user
    attrs:
      name: {{ user.name }}
      username: {{ user.username }}
      email: {{ user.username }}
      type: internal
      is_active: true
      path: users/provisioned
      groups:
{% for group in user.groups %}
        - !Find [authentik_core.group, [attributes__contains, {blueprint-id: group-{{ group | lower | replace(' ', '-')}}}]]
{% endfor %}
    conditions: []
    permissions: []
    state: present
{% endfor %}
