version: 1
metadata:
  name: Custom Site Setup - {{ site_name }}
entries:

  ####################################################
  ### Flows
  ####################################################
  
  ## Custom authentication flow
  - id: custom-authentication-flow
    identifiers:
      slug: custom-authentication-flow
    model: authentik_flows.flow
    attrs:
      name: Welcome to {{ site_name }}!
      title: Welcome to {{ site_name }}!
      designation: authentication
      authentication: none

  ## Custom enrollment flow
  - id: custom-enrollment-flow
    identifiers:
      slug: custom-source-enrollment
    model: authentik_flows.flow
    attrs:
      name: Welcome to {{ site_name }}! Please select a username.
      title: Welcome to {{ site_name }}! Please select a username.
      designation: enrollment
      authentication: none


  ####################################################
  ### Federation Sources
  ####################################################
  
  ## Google
  - id: custom-source-google
    identifiers:
      name: Google
    model: authentik_sources_oauth.oauthsource
    attrs:
      name: Google Source
      slug: google
      enabled: true
      authentication_flow: !KeyOf custom-authentication-flow
      enrollment_flow: !KeyOf custom-enrollment-flow
      consumer_key: {{ secret_auth_google_consumer_key }}
      consumer_secret: {{ secret_auth_google_consumer_secret }}
      provider_type: google
      access_token_url: https://oauth2.googleapis.com/token
      authorization_url: https://accounts.google.com/o/oauth2/v2/auth
      profile_url: https://openidconnect.googleapis.com/v1/userinfo
      request_token_url: null
      group_matching_mode: identifier
      policy_engine_mode: any
      user_matching_mode: identifier
      user_path_template: goauthentik.io/sources/%(slug)s
    conditions: []
    permissions: []
    state: present

    
  ####################################################
  ### Prompts
  ####################################################

  - id: prompt-field-username
    identifiers:
      name: custom-source-enrollment-field-username
    model: authentik_stages_prompt.prompt
    attrs:
      order: 100
      placeholder: Username
      placeholder_expression: false
      required: true
      type: username
      field_key: username
      label: Username

  
  ####################################################
  ### Stages
  ####################################################
  
  ## Authentication: MFA
  - id: custom-authentication-mfa-validation
    identifiers:
      name: custom-authentication-mfa-validation
    model: authentik_stages_authenticator_validate.authenticatorvalidatestage
  
  ## Authentication: Identification
  - id: custom-authentication-identification
    identifiers:
      name: custom-authentication-identification
    model: authentik_stages_identification.identificationstage
    state: present
    attrs:
      user_fields: []
      case_insensitive_matching: true
      pretend_user_exists: true
      show_matched_user: true
      show_source_labels: true
      sources:
        - !KeyOf custom-source-google
  
  ## Authentication: Login
  - id: custom-authentication-login
    identifiers:
      name: custom-authentication-login
    model: authentik_stages_user_login.userloginstage
  
  ## Enrollment: Login
  - id: custom-source-enrollment-login
    identifiers:
      name: custom-source-enrollment-login
    model: authentik_stages_user_login.userloginstage

  ## Enrollment: Username Prompt
  - id: custom-source-enrollment-prompt
    identifiers:
      name: custom-source-enrollment-prompt
    model: authentik_stages_prompt.promptstage
    attrs:
      fields:
      - !KeyOf prompt-field-username
        
    
  ####################################################
  ### Stage Bindings
  ####################################################

  ## Authentication: Identification
  - identifiers:
      order: 10
      stage: !KeyOf custom-authentication-identification
      target: !KeyOf custom-authentication-flow
    model: authentik_flows.flowstagebinding

  ## Authentication: MFA
  - identifiers:
      order: 30
      stage: !KeyOf custom-authentication-mfa-validation
      target: !KeyOf custom-authentication-flow
    model: authentik_flows.flowstagebinding

  ## Authentication: Login
  - identifiers:
      order: 100
      stage: !KeyOf custom-authentication-login
      target: !KeyOf custom-authentication-flow
    model: authentik_flows.flowstagebinding

  ## Enrollment: Username Prompt
  - id: prompt-binding
    model: authentik_flows.flowstagebinding
    attrs:
      re_evaluate_policies: true
    identifiers:
      order: 0
      stage: !KeyOf custom-source-enrollment-prompt
      target: !KeyOf custom-enrollment-flow

  ## Enrollment: User Write
  - id: custom-source-enrollment-write
    identifiers:
      name: custom-source-enrollment-write
    model: authentik_stages_user_write.userwritestage
    attrs:
      user_creation_mode: always_create
      user_type: internal
      
  ## Enrollment: Flow Write
  - identifiers:
      order: 1
      stage: !KeyOf custom-source-enrollment-write
      target: !KeyOf custom-enrollment-flow
    model: authentik_flows.flowstagebinding

  ## Enrollment: Login
  - identifiers:
      order: 2
      stage: !KeyOf custom-source-enrollment-login
      target: !KeyOf custom-enrollment-flow
    model: authentik_flows.flowstagebinding

      
  ####################################################
  ### Policies
  ####################################################
  
  - id: custom-source-enrollment-if-username
    identifiers:
      name: custom-source-enrollment-if-username
    model: authentik_policies_expression.expressionpolicy
    attrs:
      expression: |
        # Check if we''ve not been given a username by the external IdP
        # and trigger the enrollment flow
        return 'username' not in context.get('prompt_data', {})
  
  - id: custom-source-enrollment-if-sso
    identifiers:
      name: custom-source-enrollment-if-sso
    model: authentik_policies_expression.expressionpolicy
    attrs:
      expression: |
        # This policy ensures that this flow can only be used when the user
        # is in a SSO Flow (meaning they come from an external IdP)
        return ak_is_sso_flow
  
  - id: custom-source-enrollment-username-is-email
    identifiers:
      name: custom-source-enrollment-username-is-email
    model: authentik_policies_expression.expressionpolicy
    attrs:
      expression: |
        email = request.context["prompt_data"]["email"]
        # always use the email as the username
        request.context["prompt_data"]["username"] = email
        return False
      
    
  ####################################################
  ### Policy Bindings
  ####################################################
    
  ## Enrollment: If SSO
  - identifiers:
      order: 0
      policy: !KeyOf custom-source-enrollment-if-sso
      target: !KeyOf custom-enrollment-flow
    model: authentik_policies.policybinding
    
  ## Enrollment: Use email as username
  - identifiers:
      order: 0
      policy: !KeyOf custom-source-enrollment-username-is-email
      target: !KeyOf prompt-binding
    model: authentik_policies.policybinding

  ## Enrollment: If Username
  - identifiers:
      order: 1
      policy: !KeyOf custom-source-enrollment-if-username
      target: !KeyOf prompt-binding
    model: authentik_policies.policybinding
  
