- name: CF ({{ dns_name }}) - Create temp file
  local_action:
    module: ansible.builtin.tempfile
  register: tmp
  changed_when: false
  
- name: CF ({{ dns_name }}) - Copy script to temp file
  local_action:
    module: ansible.builtin.copy
    src: ../../../submodules/cloudflare-ddns-updater/cloudflare-template.sh
    dest: "{{ tmp.path }}"
    mode: "0644"
  changed_when: false
  
- name: CF ({{ dns_name }}) - Update script with custom settings
  local_action:
    module: ansible.builtin.blockinfile
    path: "{{ tmp.path }}"
    insertafter: "^discorduri=\"\""
    block: |
      auth_email="{{ dns_record.auth_email }}"
      auth_method="{{ dns_record.auth_method }}"
      auth_key="{{ dns_record.auth_key }}"
      zone_identifier="{{ dns_record.zone_id }}"
      record_name="{{ dns_name }}"
      ttl="{{ dns_record.ttl }}"
      proxy="{{ dns_record.proxy }}"
      sitename="{{ dns_record.sitename }}"
      slackchannel="{{ dns_record.slackchannel }}"
      slackuri="{{ dns_record.slackuri }}"
      discorduri="{{ dns_record.discorduri }}"
    prepend_newline: true
  changed_when: false
  
- name: CF ({{ dns_name }}) - Copy customized script to host
  become: false
  ansible.builtin.copy:
    src: "{{ tmp.path }}"
    dest: "{{ scripts_root }}/update_cf_dns-{{ dns_name }}.sh"
    mode: "0750"
    
- name: CF ({{ dns_name }}) - Delete temp file
  local_action:
    module: ansible.builtin.file
    path: "{{ tmp.path }}"
    state: absent
  changed_when: false

- name: CF ({{ dns_name }}) - Update crontab for {{ ansible_user }}
  become: false
  ansible.builtin.cron:
    name: "CF {{ dns_name }} Update"
    job: "{{ scripts_root }}/update_cf_dns-{{ dns_name }}.sh"
    minute: "{{ dns_record.cron.minute }}"
    hour: "{{ dns_record.cron.hour }}"
    day: "{{ dns_record.cron.day }}"
    month: "{{ dns_record.cron.month }}"
    weekday: "{{ dns_record.cron.weekday }}"
  when: '"cron" in dns_record'
