- name: Create app config directories
  # no_log: true
  ansible.builtin.file:
    path: "{{ docker_volumes_root }}/{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_community.general.filetree: ../configs
  when: item.state == "directory"
  loop_control:
    label: "{{ item.path }}"

- name: Copy app config template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ docker_volumes_root }}/{{ item.path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_community.general.filetree: ../configs
  when: item.state == "file"
  loop_control:
    label: "{{ item.path }}"

- name: Recreate app config symlinks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ docker_volumes_root }}/{{ item.path }}"
    state: link
    # avoid corrupting target files if the link already exists
    follow: false
    force: true
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_community.general.filetree: ../configs
  when: item.state == "link"
  loop_control:
    label: "{{ item.path }}"
