- name: Copy docker services compose files
  become: false
  vars:
    container_name: "{{ docker_site }}_{{ item }}"
    container_sp_name: "{{ docker_site }}_sp-{{ item }}"
    container_net_name: "{{ docker_site }}_net-{{ item }}"
    container_volume_root: "{{ docker_volumes_root }}/{{ docker_site }}/{{ item }}"
    docker_service: "{{ docker_services[item] }}"
  ansible.builtin.template:
    src: templates/{{ item }}.yml.j2
    dest: "{{ docker_compose_root }}/{{ docker_site }}_{{ item }}.yml"
    mode: 0640
  loop: "{{ docker_services.keys() }}"
  
- name: Copy docker main compose file
  become: false
  ansible.builtin.template:
    src: templates/compose.yml.j2
    dest: "{{ docker_compose_root }}/compose_{{ docker_site }}.yml"
    mode: 0640

- name: Start all docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_root }}"
    files: "compose_{{ docker_site }}.yml"
    state: present
