- name: Install LXC required system packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - lxc
      - python3
      - python3-lxc
      - libvirt0
      # - libpam-cgfs
      - bridge-utils
      - uidmap

- name: Copy LXC system-wide configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: files/lxc_default.conf, dest: /etc/lxc/default.conf }
    - { src: files/subuid, dest: /etc/subuid }
    - { src: files/subgid, dest: /etc/subgid }
    
- name: Copy LXC network configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    # - { src: files/lxc_dhcp.conf, dest: /etc/lxc/dhcp.conf }
    - { src: files/lxc_net.conf, dest: /etc/default/lxc-net }
  notify: restart lxc-net
    
- name: Check host LXC config
  ansible.builtin.command: lxc-checkconfig
  # ignore changed
  changed_when: false
