- name: Setup systcl tweaks
  become: true
  ansible.builtin.copy:
    src: files/sysctl.conf
    dest: /etc/sysctl.conf
    mode: 0644

- name: Create docker root directories
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0750 # maybe setgid bit?
  loop:
    - "{{ docker_root }}"
    - "{{ media_root }}"

- name: Create docker sub-directories
  become: true
  ansible.builtin.file:
    dest: "{{ docker_root }}/{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0750
  loop:
    - data
    - compose
    - logs
    - scripts
    - secrets

- name: Copy docker compose file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_root }}/docker-compose.yml"
    mode: 0640

- name: Copy docker services compose files
  ansible.builtin.template:
    src: templates/{{ item.key }}.yml.j2
    dest: "{{ docker_root }}/compose/{{ item.key }}.yml"
    mode: 0640
  loop: "{{ docker_services | dict2items }}"

- name: Start all docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ docker_root }}"
    files: "docker-compose.yml"
    state: present
