- name: Setup systcl tweaks
  ansible.builtin.copy:
    src: files/sysctl.conf
    dest: /etc/sysctl.conf
    mode: 0644

- name: Create root docker directories
  ansible.builtin.file:
    dest: "{{ docker_root }}/{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0750
  loop:
    - data
    - compose
    - logs
    - scripts
    - secrets

- name: Copy docker env file
  ansible.builtin.template:
    src: templates/_env.j2
    dest: "{{ docker_root }}/.env"
    mode: 0640

- name: Copy docker compose file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_root }}/docker-compose.yml"
    mode: 0640

- name: Copy socket-proxy compose file
  ansible.builtin.template:
    src: templates/socket-proxy.yml.j2
    dest: "{{ docker_root }}/compose/socket-proxy.yml"
    mode: 0640
